spring.application.name=flut-trading

server.port=8080

flut-trading.sale-price=10

# Logging configuration
logging.level.root=INFO
logging.level.com.niki.fluttrading=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
